import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import '@/styles/global.scss';
import { Footer } from '@/components/footer';
import { Header } from '@/components/header';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Audiophile E-commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={manrope.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </>
  );
}
